---
title: "Exp10-Spline Curve Models"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Register Number:19BLC1186

Name:Tarun Sidhu

Lab Exercise No:9

Date:17/5/2021

Dataset: Wage

Task:Spline Curve for given Dataset

```{r }
library(tidyverse)
library(broom)
require(splines)
library(ISLR)
attach(Wage) 
agelims<-range(Wage$age)
age.grid<-seq(from=agelims[1], to = agelims[2])

fit<-lm(wage ~ bs(age,knots = c(25,40,60)),data = Wage )
summary(fit)

plot(Wage$age,Wage$wage,col="grey",xlab="Age",ylab="Wages")
points(age.grid,predict(fit,newdata = list(age=age.grid)),col="darkgreen",lwd=2,type="l")

abline(v=c(25,40,60),lty=2,col="darkgreen")

fit1<-smooth.spline(Wage$age,Wage$wage,df=16) #16 degrees of freedom

plot(Wage$age,Wage$wage,col="grey",xlab="Age",ylab="Wages")
points(age.grid,predict(fit,newdata = list(age=age.grid)),col="darkgreen",lwd=2,type="l")

abline(v=c(25,40,60),lty=2,col="darkgreen")
lines(fit1,col="red",lwd=2)
legend("topright",c("Smoothing Spline with 16 df","Cubic Spline"),col=c("red","darkgreen"),lwd=2)

fit2<-smooth.spline(Wage$age,Wage$wage,cv = TRUE)
fit2

plot(Wage$age,Wage$wage,col="grey",xlab="Age",ylab="Wages")

lines(fit2,lwd=2,col="purple")
legend("topright",("Smoothing Splines with 6.78 df selected by CV"),col="purple",lwd=2)


```

