---
title: "Lab_4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Register Number:19BLC1186

Name:Tarun Sidhu

Lab Exercise No:4

Date:22/2/2021

Dataset: patients_data

Task: For the given dataset carry out  an analysis using Linear Discriminant Analysis and develop a model for multiclass classification. Present the ROC curve and AUC based performance metrics.


```{r cars}
library(pROC) 
library(randomForest) 

set.seed(420) 

num.samples <- 100

weight <- sort(rnorm(n=num.samples, mean=172, sd=29))

obese <- ifelse(test=(runif(n=num.samples) < (rank(weight)/num.samples)), 
  yes=1, no=0)
obese 

plot(x=weight, y=obese)

glm.fit=glm(obese ~ weight, family=binomial)
lines(weight, glm.fit$fitted.values)

roc(obese, glm.fit$fitted.values, plot=TRUE)

par(pty = "s") 

roc(obese, glm.fit$fitted.values, plot=TRUE)

roc(obese, glm.fit$fitted.values, plot=TRUE, legacy.axes=TRUE)

roc(obese, glm.fit$fitted.values, plot=TRUE, legacy.axes=TRUE, percent=TRUE, xlab="False Positive Percentage", ylab="True Postive Percentage")

roc(obese, glm.fit$fitted.values, plot=TRUE, legacy.axes=TRUE, percent=TRUE, xlab="False Positive Percentage", ylab="True Postive Percentage", col="#377eb8", lwd=4)

roc.info <- roc(obese, glm.fit$fitted.values, legacy.axes=TRUE)
str(roc.info)

roc.df <- data.frame(
  tpp=roc.info$sensitivities*100, 
  fpp=(1 - roc.info$specificities)*100, 
  thresholds=roc.info$thresholds)

head(roc.df) 

tail(roc.df) 

roc.df[roc.df$tpp > 60 & roc.df$tpp < 80,]

roc(obese, glm.fit$fitted.values, plot=TRUE, legacy.axes=TRUE, percent=TRUE, xlab="False Positive Percentage", ylab="True Postive Percentage", col="#377eb8", lwd=4, print.auc=TRUE)

roc(obese, glm.fit$fitted.values, plot=TRUE, legacy.axes=TRUE, percent=TRUE, xlab="False Positive Percentage", ylab="True Postive Percentage", col="#377eb8", lwd=4, print.auc=TRUE, print.auc.x=45, partial.auc=c(100, 90), auc.polygon = TRUE, auc.polygon.col = "#377eb822")

rf.model <- randomForest(factor(obese) ~ weight)

roc(obese, rf.model$votes[,1], plot=TRUE, legacy.axes=TRUE, percent=TRUE, xlab="False Positive Percentage", ylab="True Postive Percentage", col="#4daf4a", lwd=4, print.auc=TRUE)

roc(obese, glm.fit$fitted.values, plot=TRUE, legacy.axes=TRUE, percent=TRUE, xlab="False Positive Percentage", ylab="True Postive Percentage", col="#377eb8", lwd=4, print.auc=TRUE)

plot.roc(obese, rf.model$votes[,1], percent=TRUE, col="#4daf4a", lwd=4, print.auc=TRUE, add=TRUE, print.auc.y=40)
legend("bottomright", legend=c("Logisitic Regression", "Random Forest"), col=c("#377eb8", "#4daf4a"), lwd=4)

par(pty = "m")

```

